[tox]
envlist = lint, typecheck

[testenv:lint]
deps =
    ruff
commands =
    ruff check src/
    ruff format --check src/

[testenv:typecheck]
deps =
    mypy
    flask
commands =
    mypy --strict src/differ/app.py
